# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exam_protocol.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x65xam_protocol.proto\x12\nexam_proto\"8\n\x08\x42RD_ctrl\x12\x0f\n\x07\x63ommand\x18\x01 \x02(\x07\x12\x0b\n\x03out\x18\x02 \x02(\x07\x12\x0e\n\x06status\x18\x03 \x02(\x0f\x42\x02H\x03')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'exam_protocol_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _BRD_CTRL._serialized_start=35
  _BRD_CTRL._serialized_end=91
# @@protoc_insertion_point(module_scope)
