# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ADCLogUIDesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdcStatusWin(object):
    def setupUi(self, AdcStatusWin):
        AdcStatusWin.setObjectName("AdcStatusWin")
        AdcStatusWin.resize(505, 295)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AdcStatusWin.sizePolicy().hasHeightForWidth())
        AdcStatusWin.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(AdcStatusWin)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textBrowser = QtWidgets.QTextBrowser(AdcStatusWin)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.reboot_pushButton = QtWidgets.QPushButton(AdcStatusWin)
        self.reboot_pushButton.setObjectName("reboot_pushButton")
        self.verticalLayout.addWidget(self.reboot_pushButton)

        self.retranslateUi(AdcStatusWin)
        QtCore.QMetaObject.connectSlotsByName(AdcStatusWin)

    def retranslateUi(self, AdcStatusWin):
        _translate = QtCore.QCoreApplication.translate
        AdcStatusWin.setWindowTitle(_translate("AdcStatusWin", "ADC log"))
        self.reboot_pushButton.setText(_translate("AdcStatusWin", "reboot"))
